version: "3.1"

services:
  {{name}}-service:
    pports:
      - "8080:8080"
    networks:
      - frontend
      - backend
    build:
      context: ./
    volumes:
      - ./ui:/usr/src/app/ui/:ro

# Default network
networks:
  frontend:
  backend: